package com.woniu.pojo;
// Generated 2019-12-18 10:40:50 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

import org.springframework.stereotype.Component;

/**
 * Role generated by hbm2java
 */
@Component
public class Role implements java.io.Serializable {

	private Integer rid;
	private String rname;
	private Set users = new HashSet(0);

	public Role() {
	}

	public Role(String rname, Set users) {
		this.rname = rname;
		this.users = users;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	public String getRname() {
		return this.rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
