package com.woniu.pojo;

import org.springframework.stereotype.Component;

// Generated 2019-12-18 10:40:50 by Hibernate Tools 5.4.7.Final

/**
 * User generated by hbm2java
 */
@Component
public class User implements java.io.Serializable {

	private Integer uid;
	private String uname;
	private String upwd;
	private String uphoto;

	public User() {
	}

	public User( String uname, String upwd, String uphoto) {
	
		this.uname = uname;
		this.upwd = upwd;
		this.uphoto = uphoto;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpwd() {
		return this.upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	public String getUphoto() {
		return this.uphoto;
	}

	public void setUphoto(String uphoto) {
		this.uphoto = uphoto;
	}

}
